# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AddToPlot.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='AddToPlot.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x41\x64\x64ToPlot.proto\"c\n\tAddToPlot\x12\x13\n\x0bplot_number\x18\x01 \x02(\r\x12\x19\n\x11milliseconds_tick\x18\x02 \x02(\r\x12\x12\n\ndata_label\x18\x03 \x02(\t\x12\x12\n\ndata_point\x18\x04 \x02(\x05'
)




_ADDTOPLOT = _descriptor.Descriptor(
  name='AddToPlot',
  full_name='AddToPlot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='plot_number', full_name='AddToPlot.plot_number', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='milliseconds_tick', full_name='AddToPlot.milliseconds_tick', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_label', full_name='AddToPlot.data_label', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_point', full_name='AddToPlot.data_point', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=118,
)

DESCRIPTOR.message_types_by_name['AddToPlot'] = _ADDTOPLOT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddToPlot = _reflection.GeneratedProtocolMessageType('AddToPlot', (_message.Message,), {
  'DESCRIPTOR' : _ADDTOPLOT,
  '__module__' : 'AddToPlot_pb2'
  # @@protoc_insertion_point(class_scope:AddToPlot)
  })
_sym_db.RegisterMessage(AddToPlot)


# @@protoc_insertion_point(module_scope)
